/*
 * Shared board renderer for the post-game mosaic mockups. Draws the exact Crossy SVG
 * board (CrosswordGrid.tsx conventions: 36-unit cells, letter fontSize 24 at y+32, clue
 * numbers fontSize 10 weight 700 at x+2 y+10, --cell-block fill, --stroke hairline, a
 * 2-unit outer frame) so the mockups read as Crossy, not a wireframe. Per-cell writer
 * attribution paints a wash of the writer's roster color under the ink glyph.
 *
 * Grid data (blocks, letters, numbers, attribution, solvers) is loaded from grid.json,
 * generated by the sibling gridgen script. Every mockup embeds the same board.
 */

const CELL = 36;
const NS = "http://www.w3.org/2000/svg";

function el(name, attrs) {
  const node = document.createElementNS(NS, name);
  for (const k in attrs) node.setAttribute(k, attrs[k]);
  return node;
}

// hex -> {r,g,b}
function hex(c) {
  const h = c.replace("#", "");
  return {
    r: parseInt(h.slice(0, 2), 16),
    g: parseInt(h.slice(2, 4), 16),
    b: parseInt(h.slice(4, 6), 16),
  };
}

// A wash: the writer's color at a low alpha over the paper cell, matching iOS's washAlpha
// discipline (a tint under the glyph, never a slab). alpha in [0,1].
function wash(color, alpha) {
  const { r, g, b } = hex(color);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

/*
 * options:
 *   tint: 0..1        attribution wash intensity (0 = plain ink board, 1 = full mosaic)
 *   solidFill: bool   paint the whole cell in the writer's color (a flatter, poster look)
 *   ink: bool         draw the letters (true) or hide them for a pure color field (false)
 *   numbers: bool     draw clue numbers
 *   highlight: index  a solver index to spotlight (others dimmed) or null
 *   frameColor: css   outer frame stroke (default --board-frame)
 */
function renderBoard(grid, options = {}) {
  const {
    tint = 0,
    solidFill = false,
    ink = true,
    numbers = true,
    highlight = null,
    frameColor = "var(--board-frame)",
  } = options;

  const { cols, rows } = grid;
  const blocks = new Set(grid.blocks);
  const svg = el("svg", {
    class: "board",
    viewBox: `0 0 ${cols * CELL} ${rows * CELL}`,
    role: "img",
    "aria-label": `${cols} by ${rows} crossword mosaic`,
  });

  for (let cell = 0; cell < cols * rows; cell++) {
    const x = (cell % cols) * CELL;
    const y = Math.floor(cell / cols) * CELL;
    const isBlock = blocks.has(cell);

    const g = el("g", {});
    // base cell
    g.appendChild(
      el("rect", {
        x,
        y,
        width: CELL,
        height: CELL,
        fill: isBlock ? "var(--cell-block)" : "var(--cell-default)",
        stroke: "var(--stroke)",
        "stroke-width": 0.6,
      }),
    );

    if (!isBlock && tint > 0) {
      const solverIdx = grid.attribution[cell];
      const solver = grid.solvers[solverIdx];
      if (solver) {
        const dimmed = highlight !== null && highlight !== solverIdx;
        const a = solidFill
          ? (dimmed ? 0.06 : 0.9) * tint
          : (dimmed ? 0.04 : 0.34) * tint;
        g.appendChild(
          el("rect", {
            x,
            y,
            width: CELL,
            height: CELL,
            fill: wash(solver.color, a),
          }),
        );
      }
    }

    const number = grid.numbers[cell];
    if (numbers && number !== undefined) {
      const t = el("text", {
        x: x + 2,
        y: y + 10,
        "font-size": 10,
        "font-weight": 700,
        fill: "var(--clue-number)",
      });
      t.textContent = number;
      g.appendChild(t);
    }

    const value = grid.letters[cell];
    if (ink && value && !isBlock) {
      // On a solid-fill poster the ink flips to the panel face for contrast; on a wash it
      // stays the board's near-black letter, exactly as the live board paints it.
      const solverIdx = grid.attribution[cell];
      const dimmed = highlight !== null && highlight !== solverIdx;
      const t = el("text", {
        x: x + CELL / 2,
        y: y + 32,
        "font-size": 24,
        "text-anchor": "middle",
        fill: solidFill && tint >= 0.9 && !dimmed ? "#ffffff" : "var(--letter)",
        opacity: dimmed ? 0.35 : 1,
      });
      t.textContent = value;
      g.appendChild(t);
    }

    svg.appendChild(g);
  }

  svg.appendChild(
    el("rect", {
      class: "board-frame",
      x: 1,
      y: 1,
      width: cols * CELL - 2,
      height: rows * CELL - 2,
      fill: "none",
      stroke: frameColor,
      "stroke-width": 2,
    }),
  );

  return svg;
}

// A compact non-interactive legend / ledger of who filled how much: a roster row with a
// color swatch, name, and cell count, ordered by contribution. Returns a DOM node.
function renderLedger(grid, options = {}) {
  const { compact = false } = options;
  const order = grid.solvers
    .map((s, i) => ({ ...s, i, count: grid.counts[i] }))
    .sort((a, b) => b.count - a.count);
  const total = grid.counts.reduce((a, b) => a + b, 0);

  const wrap = document.createElement("div");
  wrap.className = compact ? "ledger ledger-compact" : "ledger";
  for (const s of order) {
    const row = document.createElement("div");
    row.className = "ledger-row";
    const pct = Math.round((s.count / total) * 100);
    row.innerHTML = `
      <span class="ledger-swatch" style="background:${s.color}"></span>
      <span class="ledger-name">${s.name}</span>
      <span class="ledger-bar"><span class="ledger-fill" style="width:${pct}%;background:${s.color}"></span></span>
      <span class="ledger-count">${s.count}</span>`;
    wrap.appendChild(row);
  }
  return wrap;
}

// Grid data is inlined by grid-inline.js (window.__GRID__) so the mockups render over
// file:// with no fetch, which Playwright screenshot needs.
function loadGrid() {
  return window.__GRID__;
}

window.Mosaic = { renderBoard, renderLedger, loadGrid };
