// The invite QR's matrix: data in, bool modules out, nothing else (iOS InviteQR.swift, itself a
// pure port of the QR generator the web already trusts — uqr, the Nayuki qrcodegen core). So the
// code a phone camera reads off an Android screen is module-for-module the code the party projector
// shows (apps/web PartyView renders the same uqr matrix) and the code an iPhone screen shows. Same
// register everywhere: ECC M (the projector's), minimal version, mask chosen by the spec's penalty
// rules, ECC boost off. Dependency-free by design (the encoder is arithmetic, no android, no third
// party), so ShareQrSheet draws it on a Compose Canvas the way iOS draws it in a SwiftUI Canvas.
//
// Pinned byte-for-byte against uqr's output in InviteQrTests (the URL vector was generated by uqr
// at ECC M, border 0, the same source iOS and the web pin against); a divergence is a bug here,
// never a reason to fork the modules.

package crossy.ui

/**
 * One encoded QR symbol: [size] x [size] modules, `true` is dark. [version] and [mask] ride along
 * so the tests can pin the encoder's choices, not just the picture. Rows are [modules]`[y][x]`.
 */
data class QrMatrix(
    val version: Int,
    val size: Int,
    val mask: Int,
    val modules: List<List<Boolean>>,
)

/** The pure QR encoder (iOS InviteQR). Encodes at ECC M, minimal version, auto mask, no ECC boost. */
object InviteQr {

    /**
     * Encode [text] at ECC M (the invite register, PartyView's choice). Numeric and alphanumeric
     * payloads take their compact modes, anything else is UTF-8 bytes, exactly uqr's mode selection.
     * Returns null only when the payload exceeds version 40's capacity, which no invite URL
     * approaches.
     */
    fun matrix(text: String): QrMatrix? {
        val segment = Segment.make(text)
        // The empty string: no segments, a valid degenerate encode in uqr (an empty version-1
        // symbol), but nothing an invite ever shares. Encode it anyway for parity.
        return encode(if (segment == null) emptyList() else listOf(segment), Ecc.MEDIUM)
    }

    // MARK: Error correction levels (uqr's EccMap pairs)

    private enum class Ecc(val tableRow: Int, val formatBits: Int) {
        LOW(0, 1),
        MEDIUM(1, 0),
        QUARTILE(2, 3),
        HIGH(3, 2),
    }

    // MARK: Segments (mode selection, uqr's makeSegments)

    private class Segment(
        val modeBits: Int,
        // Char-count bits for versions 1-9, 10-26, 27-40.
        val ccbits1: Int,
        val ccbits2: Int,
        val ccbits3: Int,
        val numChars: Int,
        val bits: List<Boolean>,
    ) {
        fun charCountBits(version: Int): Int = when {
            version <= 9 -> ccbits1
            version <= 26 -> ccbits2
            else -> ccbits3
        }

        companion object {
            const val ALPHANUMERIC_CHARSET = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ \$%*+-./:"

            fun make(text: String): Segment? {
                if (text.isEmpty()) return null
                // ASCII digits only (Swift isASCII && isNumber): the compact numeric mode.
                if (text.all { it.code in 0x30..0x39 }) return numeric(text)
                if (text.all { it in ALPHANUMERIC_CHARSET }) return alphanumeric(text)
                return bytes(text.toByteArray(Charsets.UTF_8))
            }

            private fun numeric(digits: String): Segment {
                val bits = ArrayList<Boolean>()
                var i = 0
                while (i < digits.length) {
                    val n = minOf(digits.length - i, 3)
                    val value = digits.substring(i, i + n).toInt()
                    appendBits(value, n * 3 + 1, bits)
                    i += n
                }
                return Segment(0x1, 10, 12, 14, digits.length, bits)
            }

            private fun alphanumeric(text: String): Segment {
                val indices = text.map { ALPHANUMERIC_CHARSET.indexOf(it) }
                val bits = ArrayList<Boolean>()
                var i = 0
                while (i + 2 <= indices.size) {
                    appendBits(indices[i] * 45 + indices[i + 1], 11, bits)
                    i += 2
                }
                if (i < indices.size) appendBits(indices[i], 6, bits)
                return Segment(0x2, 9, 11, 13, indices.size, bits)
            }

            private fun bytes(data: ByteArray): Segment {
                val bits = ArrayList<Boolean>()
                for (byte in data) appendBits(byte.toInt() and 0xFF, 8, bits)
                return Segment(0x4, 8, 16, 16, data.size, bits)
            }
        }
    }

    // MARK: Capacity tables (the spec's, via uqr)

    private val eccCodewordsPerBlock: Array<IntArray> = arrayOf(
        intArrayOf(-1, 7, 10, 15, 20, 26, 18, 20, 24, 30, 18, 20, 24, 26, 30, 22, 24, 28, 30, 28, 28, 28, 28, 30, 30, 26, 28, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30),
        intArrayOf(-1, 10, 16, 26, 18, 24, 16, 18, 22, 22, 26, 30, 22, 22, 24, 24, 28, 28, 26, 26, 26, 26, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28),
        intArrayOf(-1, 13, 22, 18, 26, 18, 24, 18, 22, 20, 24, 28, 26, 24, 20, 30, 24, 28, 28, 26, 30, 28, 30, 30, 30, 30, 28, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30),
        intArrayOf(-1, 17, 28, 22, 16, 22, 28, 26, 26, 24, 28, 24, 28, 22, 24, 24, 30, 28, 28, 26, 28, 30, 24, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30),
    )

    private val numErrorCorrectionBlocks: Array<IntArray> = arrayOf(
        intArrayOf(-1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 4, 4, 4, 4, 4, 6, 6, 6, 6, 7, 8, 8, 9, 9, 10, 12, 12, 12, 13, 14, 15, 16, 17, 18, 19, 19, 20, 21, 22, 24, 25),
        intArrayOf(-1, 1, 1, 1, 2, 2, 4, 4, 4, 5, 5, 5, 8, 9, 9, 10, 10, 11, 13, 14, 16, 17, 17, 18, 20, 21, 23, 25, 26, 28, 29, 31, 33, 35, 37, 38, 40, 43, 45, 47, 49),
        intArrayOf(-1, 1, 1, 2, 2, 4, 4, 6, 6, 8, 8, 8, 10, 12, 16, 12, 17, 16, 18, 21, 20, 23, 23, 25, 27, 29, 34, 34, 35, 38, 40, 43, 45, 48, 51, 53, 56, 59, 62, 65, 68),
        intArrayOf(-1, 1, 1, 2, 4, 4, 4, 5, 6, 8, 8, 11, 11, 16, 16, 18, 16, 19, 21, 25, 25, 25, 34, 30, 32, 35, 37, 40, 42, 45, 48, 51, 54, 57, 60, 63, 66, 70, 74, 77, 81),
    )

    private fun numRawDataModules(version: Int): Int {
        var result = (16 * version + 128) * version + 64
        if (version >= 2) {
            val numAlign = version / 7 + 2
            result -= (25 * numAlign - 10) * numAlign - 55
            if (version >= 7) result -= 36
        }
        return result
    }

    private fun numDataCodewords(version: Int, ecc: Ecc): Int =
        numRawDataModules(version) / 8 -
            eccCodewordsPerBlock[ecc.tableRow][version] * numErrorCorrectionBlocks[ecc.tableRow][version]

    // MARK: Encoding (uqr's encodeSegments; no ECC boost, auto mask)

    private fun encode(segments: List<Segment>, ecc: Ecc): QrMatrix? {
        // Minimal version that fits (the projector's posture: boostEcc off).
        var version = 1
        while (true) {
            val capacityBits = numDataCodewords(version, ecc) * 8
            val used = totalBits(segments, version)
            if (used != null && used <= capacityBits) break
            if (version >= 40) return null
            version += 1
        }

        val bits = ArrayList<Boolean>()
        for (segment in segments) {
            appendBits(segment.modeBits, 4, bits)
            appendBits(segment.numChars, segment.charCountBits(version), bits)
            bits.addAll(segment.bits)
        }

        // Terminator, byte alignment, then the spec's alternating pad bytes.
        val capacityBits = numDataCodewords(version, ecc) * 8
        appendBits(0, minOf(4, capacityBits - bits.size), bits)
        appendBits(0, (8 - bits.size % 8) % 8, bits)
        var padByte = 0xEC
        while (bits.size < capacityBits) {
            appendBits(padByte, 8, bits)
            padByte = padByte xor (0xEC xor 0x11)
        }

        val dataCodewords = IntArray(bits.size / 8)
        for (i in bits.indices) if (bits[i]) dataCodewords[i shr 3] = dataCodewords[i shr 3] or (1 shl (7 - (i and 7)))

        return Symbol(version, ecc, dataCodewords).matrix()
    }

    private fun totalBits(segments: List<Segment>, version: Int): Int? {
        var result = 0
        for (segment in segments) {
            val ccbits = segment.charCountBits(version)
            if (segment.numChars >= (1 shl ccbits)) return null
            result += 4 + ccbits + segment.bits.size
        }
        return result
    }

    private fun appendBits(value: Int, length: Int, bits: MutableList<Boolean>) {
        if (length <= 0) return
        for (i in length - 1 downTo 0) bits.add((value shr i) and 1 != 0)
    }

    // MARK: The symbol (drawing, masking, penalty)

    private class Symbol(val version: Int, val ecc: Ecc, dataCodewords: IntArray) {
        val size: Int = version * 4 + 17
        // modules[y][x]; isFunction[y][x] guards the function cells from data and masking.
        val modules: Array<BooleanArray> = Array(size) { BooleanArray(size) }
        val isFunction: Array<BooleanArray> = Array(size) { BooleanArray(size) }

        init {
            drawFunctionPatterns()
            drawCodewords(addEccAndInterleave(dataCodewords))
        }

        /** Choose the mask by the spec's four penalty rules (uqr's automask), apply it, return. */
        fun matrix(): QrMatrix {
            var chosen = -1
            var minPenalty = Int.MAX_VALUE
            for (candidate in 0 until 8) {
                applyMask(candidate)
                drawFormatBits(candidate)
                val penalty = penaltyScore()
                if (penalty < minPenalty) {
                    chosen = candidate
                    minPenalty = penalty
                }
                applyMask(candidate) // XOR undoes itself
            }
            applyMask(chosen)
            drawFormatBits(chosen)
            return QrMatrix(version, size, chosen, modules.map { it.toList() })
        }

        // MARK: Function patterns

        private fun drawFunctionPatterns() {
            for (i in 0 until size) {
                setFunction(6, i, i % 2 == 0)
                setFunction(i, 6, i % 2 == 0)
            }
            drawFinder(3, 3)
            drawFinder(size - 4, 3)
            drawFinder(3, size - 4)
            val positions = alignmentPatternPositions()
            val count = positions.size
            for (i in 0 until count) {
                for (j in 0 until count) {
                    val corner = (i == 0 && j == 0) || (i == 0 && j == count - 1) || (i == count - 1 && j == 0)
                    if (!corner) drawAlignment(positions[i], positions[j])
                }
            }
            drawFormatBits(0)
            drawVersion()
        }

        private fun drawFormatBits(mask: Int) {
            val data = ecc.formatBits shl 3 or mask
            var rem = data
            repeat(10) { rem = (rem shl 1) xor ((rem shr 9) * 0x537) }
            val bits = (data shl 10 or rem) xor 0x5412
            for (i in 0..5) setFunction(8, i, bit(bits, i))
            setFunction(8, 7, bit(bits, 6))
            setFunction(8, 8, bit(bits, 7))
            setFunction(7, 8, bit(bits, 8))
            for (i in 9 until 15) setFunction(14 - i, 8, bit(bits, i))
            for (i in 0 until 8) setFunction(size - 1 - i, 8, bit(bits, i))
            for (i in 8 until 15) setFunction(8, size - 15 + i, bit(bits, i))
            setFunction(8, size - 8, true)
        }

        private fun drawVersion() {
            if (version < 7) return
            var rem = version
            repeat(12) { rem = (rem shl 1) xor ((rem shr 11) * 0x1F25) }
            val bits = version shl 12 or rem
            for (i in 0 until 18) {
                val color = bit(bits, i)
                val a = size - 11 + i % 3
                val b = i / 3
                setFunction(a, b, color)
                setFunction(b, a, color)
            }
        }

        private fun drawFinder(x: Int, y: Int) {
            for (dy in -4..4) {
                for (dx in -4..4) {
                    val dist = maxOf(kotlin.math.abs(dx), kotlin.math.abs(dy))
                    val xx = x + dx
                    val yy = y + dy
                    if (xx in 0 until size && yy in 0 until size) setFunction(xx, yy, dist != 2 && dist != 4)
                }
            }
        }

        private fun drawAlignment(x: Int, y: Int) {
            for (dy in -2..2) {
                for (dx in -2..2) setFunction(x + dx, y + dy, maxOf(kotlin.math.abs(dx), kotlin.math.abs(dy)) != 1)
            }
        }

        private fun setFunction(x: Int, y: Int, isDark: Boolean) {
            modules[y][x] = isDark
            isFunction[y][x] = true
        }

        private fun alignmentPatternPositions(): List<Int> {
            if (version <= 1) return emptyList()
            val numAlign = version / 7 + 2
            val step = if (version == 32) 26 else (version * 4 + numAlign * 2 + 1) / (numAlign * 2 - 2) * 2
            val result = ArrayList<Int>()
            result.add(6)
            var pos = size - 7
            while (result.size < numAlign) {
                result.add(1, pos)
                pos -= step
            }
            return result
        }

        // MARK: Codewords

        private fun addEccAndInterleave(data: IntArray): IntArray {
            val numBlocks = numErrorCorrectionBlocks[ecc.tableRow][version]
            val blockEccLen = eccCodewordsPerBlock[ecc.tableRow][version]
            val rawCodewords = numRawDataModules(version) / 8
            val numShortBlocks = numBlocks - rawCodewords % numBlocks
            val shortBlockLen = rawCodewords / numBlocks

            val blocks = ArrayList<IntArray>()
            val divisor = reedSolomonDivisor(blockEccLen)
            var k = 0
            for (i in 0 until numBlocks) {
                val length = shortBlockLen - blockEccLen + if (i < numShortBlocks) 0 else 1
                val dat = data.copyOfRange(k, k + length)
                k += length
                val eccBytes = reedSolomonRemainder(dat, divisor)
                // Short blocks carry a padding 0 so every block ends the same length; the interleave
                // skips that column below.
                val block = IntArray(shortBlockLen + 1)
                for (idx in dat.indices) block[idx] = dat[idx]
                val eccStart = if (i < numShortBlocks) length + 1 else length
                for (idx in eccBytes.indices) block[eccStart + idx] = eccBytes[idx]
                blocks.add(block)
            }

            val result = ArrayList<Int>()
            for (i in 0 until blocks[0].size) {
                for (j in blocks.indices) {
                    if (i != shortBlockLen - blockEccLen || j >= numShortBlocks) result.add(blocks[j][i])
                }
            }
            return result.toIntArray()
        }

        private fun drawCodewords(data: IntArray) {
            var i = 0
            var right = size - 1
            while (right >= 1) {
                if (right == 6) right = 5
                for (vert in 0 until size) {
                    for (j in 0 until 2) {
                        val x = right - j
                        val upward = ((right + 1) and 2) == 0
                        val y = if (upward) size - 1 - vert else vert
                        if (!isFunction[y][x] && i < data.size * 8) {
                            modules[y][x] = bit(data[i shr 3], 7 - (i and 7))
                            i += 1
                        }
                    }
                }
                right -= 2
            }
        }

        private fun applyMask(mask: Int) {
            for (y in 0 until size) {
                for (x in 0 until size) {
                    if (isFunction[y][x]) continue
                    val invert = when (mask) {
                        0 -> (x + y) % 2 == 0
                        1 -> y % 2 == 0
                        2 -> x % 3 == 0
                        3 -> (x + y) % 3 == 0
                        4 -> (x / 3 + y / 2) % 2 == 0
                        5 -> x * y % 2 + x * y % 3 == 0
                        6 -> (x * y % 2 + x * y % 3) % 2 == 0
                        else -> ((x + y) % 2 + x * y % 3) % 2 == 0
                    }
                    if (invert) modules[y][x] = !modules[y][x]
                }
            }
        }

        // MARK: Penalty (the spec's four rules)

        private fun penaltyScore(): Int {
            var result = 0

            // Rule 1 and 3, rows then columns.
            for (y in 0 until size) {
                var runColor = false
                var runLength = 0
                val history = IntArray(7)
                for (x in 0 until size) {
                    if (modules[y][x] == runColor) {
                        runLength += 1
                        if (runLength == 5) result += PENALTY_N1 else if (runLength > 5) result += 1
                    } else {
                        finderPenaltyAddHistory(runLength, history)
                        if (!runColor) result += finderPenaltyCountPatterns(history) * PENALTY_N3
                        runColor = modules[y][x]
                        runLength = 1
                    }
                }
                result += finderPenaltyTerminateAndCount(runColor, runLength, history) * PENALTY_N3
            }
            for (x in 0 until size) {
                var runColor = false
                var runLength = 0
                val history = IntArray(7)
                for (y in 0 until size) {
                    if (modules[y][x] == runColor) {
                        runLength += 1
                        if (runLength == 5) result += PENALTY_N1 else if (runLength > 5) result += 1
                    } else {
                        finderPenaltyAddHistory(runLength, history)
                        if (!runColor) result += finderPenaltyCountPatterns(history) * PENALTY_N3
                        runColor = modules[y][x]
                        runLength = 1
                    }
                }
                result += finderPenaltyTerminateAndCount(runColor, runLength, history) * PENALTY_N3
            }

            // Rule 2: 2x2 blocks of one color.
            for (y in 0 until size - 1) {
                for (x in 0 until size - 1) {
                    val color = modules[y][x]
                    if (color == modules[y][x + 1] && color == modules[y + 1][x] && color == modules[y + 1][x + 1]) {
                        result += PENALTY_N2
                    }
                }
            }

            // Rule 4: dark-module balance.
            var dark = 0
            for (row in modules) for (cell in row) if (cell) dark += 1
            val total = size * size
            val k = (kotlin.math.abs(dark * 20 - total * 10) + total - 1) / total - 1
            result += k * PENALTY_N4
            return result
        }

        private fun finderPenaltyCountPatterns(history: IntArray): Int {
            val n = history[1]
            val core = n > 0 && history[2] == n && history[3] == n * 3 && history[4] == n && history[5] == n
            return (if (core && history[0] >= n * 4 && history[6] >= n) 1 else 0) +
                (if (core && history[6] >= n * 4 && history[0] >= n) 1 else 0)
        }

        private fun finderPenaltyTerminateAndCount(currentRunColor: Boolean, currentRunLength: Int, history: IntArray): Int {
            var runLength = currentRunLength
            if (currentRunColor) {
                finderPenaltyAddHistory(runLength, history)
                runLength = 0
            }
            runLength += size
            finderPenaltyAddHistory(runLength, history)
            return finderPenaltyCountPatterns(history)
        }

        private fun finderPenaltyAddHistory(currentRunLength: Int, history: IntArray) {
            var runLength = currentRunLength
            if (history[0] == 0) runLength += size
            for (k in 6 downTo 1) history[k] = history[k - 1]
            history[0] = runLength
        }

        private fun bit(value: Int, index: Int): Boolean = (value shr index) and 1 != 0

        // MARK: Reed-Solomon (GF(2^8), the spec's field)

        private fun reedSolomonDivisor(degree: Int): IntArray {
            val result = IntArray(degree)
            result[degree - 1] = 1
            var root = 1
            for (i in 0 until degree) {
                for (j in result.indices) {
                    result[j] = reedSolomonMultiply(result[j], root)
                    if (j + 1 < result.size) result[j] = result[j] xor result[j + 1]
                }
                root = reedSolomonMultiply(root, 2)
            }
            return result
        }

        private fun reedSolomonRemainder(data: IntArray, divisor: IntArray): IntArray {
            val result = IntArray(divisor.size)
            for (byte in data) {
                val factor = byte xor result[0]
                for (i in 0 until result.size - 1) result[i] = result[i + 1]
                result[result.size - 1] = 0
                for (i in divisor.indices) result[i] = result[i] xor reedSolomonMultiply(divisor[i], factor)
            }
            return result
        }

        private fun reedSolomonMultiply(x: Int, y: Int): Int {
            var z = 0
            for (i in 7 downTo 0) {
                z = (z shl 1) xor ((z shr 7) * 0x11D)
                z = z xor (((y shr i) and 1) * x)
            }
            return z
        }

        private companion object {
            const val PENALTY_N1 = 3
            const val PENALTY_N2 = 3
            const val PENALTY_N3 = 40
            const val PENALTY_N4 = 10
        }
    }
}
