import XCTest

@testable import CrossyDesign

// Pins the FNV-1a identity hash against ground truth generated by executing the
// canonical implementation itself (apps/session/src/color.ts, root DESIGN.md §8):
// a node script imported `colorForUser`, cross-checked a replicated `fnv1a` against
// it for every fixture, and printed hash, wire hex, and mod-12 slot. Any drift here
// is a cross-client identity break: the same user would color differently on iOS
// than on the web.

final class IdentityHashTests: XCTestCase {
    /// user_id -> (fnv1a32 hash, today's wire color `#` + low 24 bits, hash % 12).
    /// Generated 2026-07-10 from apps/session/src/color.ts via node.
    private static let fixtures: [(userId: String, hash: UInt32, wireHex: String, slot: Int)] = [
        ("00000000-0000-0000-0000-000000000000", 0xBE47_8ED1, "#478ED1", 9),
        ("9f46807f-c1c5-4b8d-8302-2e1dfb51e30f", 0xE583_471A, "#83471A", 10),
        ("3c1c0f6e-3f4a-4a1e-9c86-2a54f4f0a5b2", 0x564F_925F, "#4F925F", 7),
        ("b1de8cbe-1b28-4d70-9b37-8f3d3038a1b6", 0x6F94_3ACF, "#943ACF", 11),
        ("5b0b7a52-4c53-4d3f-9f5a-0c86a9e2d914", 0x54C4_5D1E, "#C45D1E", 10),
        ("e7a0f8d1-6f92-4b8c-8a3d-52c91b7e4f06", 0x1324_0D13, "#240D13", 3),
        ("c0a8e1f2-9d34-4c56-b789-0a1b2c3d4e5f", 0xA8B2_A181, "#B2A181", 9),
        ("1a2b3c4d-5e6f-4a8b-9c0d-e1f203a4b5c6", 0x56DC_FA7C, "#DCFA7C", 8),
        ("d4c3b2a1-f6e5-4d8c-a9b8-c7d6e5f40312", 0x09EF_8704, "#EF8704", 0),
        ("7fffffff-ffff-4fff-bfff-ffffffffffff", 0xE023_B8CA, "#23B8CA", 6),
    ]

    // Root DESIGN.md §8: identity color is stable across devices, sessions, and
    // clients. The hash values are the web's own output, so equality here is the
    // cross-client contract.
    func test_fnv1a32_matchesSessionColorTs_fixtures_rootDESIGN8() {
        for fixture in Self.fixtures {
            XCTAssertEqual(
                IdentityHash.fnv1a32(fixture.userId),
                fixture.hash,
                "hash drifted from apps/session/src/color.ts for \(fixture.userId)"
            )
        }
    }

    // Today's ratified wire behavior: colorForUser = "#" + (hash & 0xffffff),
    // uppercase. Pinned via RGBColor's formatter so the full 32-bit hash, the 24-bit
    // truncation, and the hex formatting all agree with the server.
    func test_wireColorDerivation_matchesColorForUser_fixtures_rootDESIGN8() {
        for fixture in Self.fixtures {
            let wire = RGBColor(IdentityHash.fnv1a32(fixture.userId) & 0xFFFFFF)
            XCTAssertEqual(wire.hexString, fixture.wireHex, "wire hex drifted for \(fixture.userId)")
        }
    }

    // The proposed roster mapping (apps/ios/DESIGN.md §3): slot = hash mod 12.
    // Slots here were computed from the web's own hash values.
    func test_rosterSlot_isHashMod12_fixtures_rootDESIGN8() {
        for fixture in Self.fixtures {
            XCTAssertEqual(
                IdentityRoster.slot(for: fixture.userId),
                fixture.slot,
                "slot drifted for \(fixture.userId)"
            )
            XCTAssertEqual(
                IdentityRoster.color(for: fixture.userId),
                IdentityRoster.colors[fixture.slot]
            )
        }
    }

    // INV-1: bytewise ASCII, no locale, no case folding. The uppercase twin of a
    // fixture id hashes differently (value from the same node run), so any future
    // "helpful" normalization breaks loudly.
    func test_hashIsCaseSensitive_noFolding_INV1() {
        XCTAssertEqual(
            IdentityHash.fnv1a32("9F46807F-C1C5-4B8D-8302-2E1DFB51E30F"),
            0x0FD2_335A
        )
        XCTAssertNotEqual(
            IdentityHash.fnv1a32("9F46807F-C1C5-4B8D-8302-2E1DFB51E30F"),
            IdentityHash.fnv1a32("9f46807f-c1c5-4b8d-8302-2e1dfb51e30f")
        )
    }

    // The empty string hashes to the offset basis by definition; pins the constant
    // itself against the same node run (INV-1: pure arithmetic, no ambient input).
    func test_emptyString_hashesToOffsetBasis_INV1() {
        XCTAssertEqual(IdentityHash.fnv1a32(""), IdentityHash.fnv1a32OffsetBasis)
        XCTAssertEqual(IdentityHash.fnv1a32(""), 0x811C_9DC5)
    }

    // Determinism across calls and instances (root DESIGN.md §8: stable across
    // sessions): same input, same hash, always.
    func test_hashIsDeterministic_rootDESIGN8_INV1() {
        let id = "9f46807f-c1c5-4b8d-8302-2e1dfb51e30f"
        XCTAssertEqual(IdentityHash.fnv1a32(id), IdentityHash.fnv1a32(id))
    }
}
